# Generated by Django 4.2.2 on 2023-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(default='', upload_to='thumbnail/')),
                ('heading_1', models.CharField(max_length=100, null=True)),
                ('h1_content', models.CharField(max_length=5000, null=True)),
                ('heading_2', models.CharField(max_length=100, null=True)),
                ('h2_content', models.CharField(max_length=5000, null=True)),
                ('heading_3', models.CharField(max_length=100, null=True)),
                ('h3_content', models.CharField(max_length=5000, null=True)),
                ('heading_4', models.CharField(max_length=100, null=True)),
                ('h4_content', models.CharField(max_length=5000, null=True)),
                ('content_img', models.ImageField(default='', null=True, upload_to='content_img/')),
            ],
        ),
    ]
