# Generated by Django 4.2.2 on 2023-06-08 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_blogs_code_text_alter_blogs_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
