# Generated by Django 4.2.2 on 2023-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_blogs_desc_alter_blogs_code_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='ending',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
